# Generated by Django 2.2.4 on 2019-11-13 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('lost', 'Lost')], max_length=50)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Charge')),
            ],
        ),
    ]
