# Generated by Django 2.2.4 on 2019-11-13 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
        ('checkout', '0004_auto_20191113_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Transaction')),
            ],
        ),
    ]
