# Generated by Django 2.2.4 on 2019-11-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_lineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='quantity',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
