# Generated by Django 2.2.7 on 2019-11-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20191113_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='quantity',
        ),
    ]
