# Generated by Django 2.2.7 on 2019-12-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_lineitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='quantity',
        ),
    ]
