# Generated by Django 2.2.7 on 2019-12-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_remove_lineitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='transaction_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charge',
            name='postcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='charge',
            name='street_address2',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
