# Generated by Django 2.2.7 on 2019-11-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Origin',
        ),
    ]
