# Generated by Django 2.2.7 on 2019-11-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191120_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Origin'),
            preserve_default=False,
        ),
    ]
